spring:
  application:
    name: post-service

  jpa:
    generate-ddl: false
    open-in-view: false
  datasource:
    url: jdbc:postgresql://localhost:5432/post_db?currentSchema=schema_post
    #url: jdbc:postgresql://91.197.98.213:5432/post_db?currentSchema=schema_post
    username: postgre_user
    password: postgre_secret_password
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 10000

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yml

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9094}
    post-service-topic: post


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
    metrics:
      enabled: true

server:
  port: 0