spring:
  application:
    name: post-service

  jpa:
    generate-ddl: false
    open-in-view: false
  datasource:
    url: jdbc:postgresql://localhost:5432/post_db
    #url: jdbc:postgresql://91.197.98.213:5432/post_db
    username: postgre_user
    password: postgre_secret_password
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 10000


  liquibase:
    change-log: classpath:/db/changelog/create-tables.yml

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9094}
    post-service-topic: post



eureka:
  client:
    serviceUrl:
     defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
     #defaultZone: http://host.docker.internal:8761/eureka/

  instance:
    preferIpAddress: true

server:
  port: 8082