services:
  psql:
    image: postgres:latest
    container_name: postgres_db
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=postgre_user
      - POSTGRES_PASSWORD=postgre_secret_password
      - POSTGRES_MULTIPLE_DATABASES=post_db,notification_db,geo_country_db,friend_db,dialog_db,authorization_db,account_db
    volumes:
      - ./pg-init-scripts:/docker-entrypoint-initdb.d
      - database-data:/var/lib/postgresql/data

volumes:
  database-data: